FROM ubuntu:24.04
RUN apt-get update && apt-get install -y openssh-server
# Configure SSH
RUN mkdir /var/run/sshd
RUN echo 'root:toor' | chpasswd
#password for user login
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
EXPOSE 22
# Start SSH server
CMD ["/usr/sbin/sshd", "-D"]



# podman build -f Dockerfile.ssh_server  -t ssh_server .
# podman network create --subnet=172.18.0.0/29 my_custom_network
# ./run_ssh_server.sh
# podman run -dit --net my_custom_network --ip 172.18.0.1 -p 3000:22 --name ssh_server ssh_server:latest
# ssh root@172.18.0.1 -p 3000


